[package]
name = "reselim/base64"
description = "A pretty fast Luau Base64 encoder"
version = "2.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "Base64.lua"]