[package]
name = "reselim/base64"
description = "A pretty fast Luau Base64 encoder"
version = "3.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "Base64.lua"]